'use strict';

const fs = require('node:fs');
const path = require('node:path');
const pg = require('pg');

// Parse INT8 (BIGINT) as integer numbers in JavaScript
pg.types.setTypeParser(20, (val) => (val === null ? null : Number.parseInt(val, 10)));
// Parse FLOAT8 / NUMERIC
pg.types.setTypeParser(701, (val) => (val === null ? null : Number.parseFloat(val)));

const SCHEMA_SQL = `
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('government','hospital','corporate','bank')),
  address TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  radius_m INTEGER NOT NULL DEFAULT 150,
  open_min INTEGER NOT NULL,
  close_min INTEGER NOT NULL,
  slot_minutes INTEGER NOT NULL DEFAULT 15
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  slot_capacity INTEGER NOT NULL DEFAULT 4,
  avg_service_min INTEGER NOT NULL DEFAULT 6
);
CREATE INDEX IF NOT EXISTS ix_services_org ON services(org_id);

CREATE TABLE IF NOT EXISTS counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','paused','closed')),
  current_booking_id BIGINT
);
CREATE INDEX IF NOT EXISTS ix_counters_org ON counters(org_id);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  password_hash TEXT,
  google_sub TEXT UNIQUE,
  supabase_uid TEXT UNIQUE,
  totp_secret_enc TEXT,
  totp_enabled INTEGER NOT NULL DEFAULT 0,
  totp_last_step BIGINT NOT NULL DEFAULT 0,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','staff','admin','system')),
  strikes INTEGER NOT NULL DEFAULT 0,
  blocked_until BIGINT,
  org_id BIGINT REFERENCES organizations(id),
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users(lower(email));
CREATE INDEX IF NOT EXISTS ix_users_supabase_uid ON users(supabase_uid);

CREATE TABLE IF NOT EXISTS sessions (
  id_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mfa_ok INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  org_id BIGINT NOT NULL REFERENCES organizations(id),
  service_id BIGINT NOT NULL REFERENCES services(id),
  date TEXT NOT NULL,
  slot_index INTEGER NOT NULL,
  seat INTEGER NOT NULL,
  token_no INTEGER NOT NULL,
  token_code TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('appointment','walkin')),
  status TEXT NOT NULL CHECK (status IN ('booked','checked_in','called','done','no_show','cancelled')),
  counter_id BIGINT REFERENCES counters(id),
  deferrals INTEGER NOT NULL DEFAULT 0,
  reschedules INTEGER NOT NULL DEFAULT 0,
  reminder_sent INTEGER NOT NULL DEFAULT 0,
  away_since BIGINT,
  last_distance_m DOUBLE PRECISION,
  last_seen_at BIGINT,
  created_at BIGINT NOT NULL,
  checked_in_at BIGINT,
  called_at BIGINT,
  completed_at BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_bookings_seat
  ON bookings(service_id, date, slot_index, seat)
  WHERE status NOT IN ('cancelled','no_show');

CREATE INDEX IF NOT EXISTS ix_bookings_day ON bookings(org_id, date, status);
CREATE INDEX IF NOT EXISTS ix_bookings_user ON bookings(user_id, status);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  booking_id BIGINT,
  type TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'info',
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  read_at BIGINT
);
CREATE INDEX IF NOT EXISTS ix_notifications_user ON notifications(user_id, created_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  action TEXT NOT NULL,
  detail TEXT,
  ip TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS ix_audit_created ON audit_log(created_at);

CREATE TABLE IF NOT EXISTS risk_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  ip TEXT,
  score DOUBLE PRECISION,
  verdict TEXT NOT NULL,
  outcome TEXT NOT NULL,
  reasons TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_risk_created ON risk_events(created_at);
`;

const RLS_SQL = `
-- Row Level Security (RLS) policies for Supabase Postgres
ALTER TABLE IF EXISTS organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS risk_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'organizations' AND policyname = 'organizations_public_read') THEN
    CREATE POLICY organizations_public_read ON organizations FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'services' AND policyname = 'services_public_read') THEN
    CREATE POLICY services_public_read ON services FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'counters' AND policyname = 'counters_public_read') THEN
    CREATE POLICY counters_public_read ON counters FOR SELECT USING (true);
  END IF;
END $$;
`;

const TABLES = [
  {
    name: 'organizations',
    cols: ['id', 'name', 'category', 'address', 'lat', 'lng', 'radius_m', 'open_min', 'close_min', 'slot_minutes'],
    seq: 'organizations_id_seq',
  },
  {
    name: 'services',
    cols: ['id', 'org_id', 'name', 'code', 'slot_capacity', 'avg_service_min'],
    seq: 'services_id_seq',
  },
  {
    name: 'counters',
    cols: ['id', 'org_id', 'name', 'status', 'current_booking_id'],
    seq: 'counters_id_seq',
  },
  {
    name: 'users',
    cols: ['id', 'email', 'name', 'password_hash', 'google_sub', 'totp_secret_enc', 'totp_enabled', 'totp_last_step', 'role', 'strikes', 'blocked_until', 'org_id', 'created_at'],
    seq: 'users_id_seq',
  },
  {
    name: 'sessions',
    cols: ['id_hash', 'user_id', 'mfa_ok', 'created_at', 'expires_at'],
    seq: null,
  },
  {
    name: 'bookings',
    cols: ['id', 'user_id', 'org_id', 'service_id', 'date', 'slot_index', 'seat', 'token_no', 'token_code', 'kind', 'status', 'counter_id', 'deferrals', 'reschedules', 'reminder_sent', 'away_since', 'last_distance_m', 'last_seen_at', 'created_at', 'checked_in_at', 'called_at', 'completed_at'],
    seq: 'bookings_id_seq',
  },
  {
    name: 'notifications',
    cols: ['id', 'user_id', 'booking_id', 'type', 'level', 'title', 'body', 'created_at', 'read_at'],
    seq: 'notifications_id_seq',
  },
  {
    name: 'audit_log',
    cols: ['id', 'user_id', 'action', 'detail', 'ip', 'created_at'],
    seq: 'audit_log_id_seq',
  },
  {
    name: 'risk_events',
    cols: ['id', 'action', 'ip', 'score', 'verdict', 'outcome', 'reasons', 'created_at'],
    seq: 'risk_events_id_seq',
  },
];

async function migrateData(sqliteDb, pgClientOrPool, { reset = false } = {}) {
  console.log('[migrate] Initializing Postgres schema...');
  await pgClientOrPool.query(SCHEMA_SQL);

  const stats = {};

  for (const table of TABLES) {
    const sqliteRows = sqliteDb.prepare(`SELECT * FROM "${table.name}"`).all();
    console.log(`[migrate] Transferring ${table.name} (${sqliteRows.length} rows)...`);

    if (reset) {
      await pgClientOrPool.query(`DELETE FROM "${table.name}"`);
    }

    if (sqliteRows.length > 0) {
      const colList = table.cols.map((c) => `"${c}"`).join(', ');
      for (const row of sqliteRows) {
        const values = table.cols.map((col) => {
          let val = row[col];
          if (val === undefined) val = null;
          return val;
        });
        const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');
        const query = `INSERT INTO "${table.name}" (${colList}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`;
        await pgClientOrPool.query(query, values);
      }
    }

    if (table.seq) {
      try {
        await pgClientOrPool.query(
          `SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT MAX(id) FROM "${table.name}"), 1))`,
          [table.name]
        );
      } catch {
        // Fallback for pg-mem or direct sequence name
        try {
          await pgClientOrPool.query(
            `SELECT setval('${table.name}_id_seq', COALESCE((SELECT MAX(id) FROM "${table.name}"), 1))`
          );
        } catch {
          // ignore sequence error if not supported in emulator
        }
      }
    }

    const countRes = await pgClientOrPool.query(`SELECT COUNT(*) AS c FROM "${table.name}"`);
    const pgCount = Number.parseInt(countRes.rows[0].c, 10);
    stats[table.name] = { sqlite: sqliteRows.length, postgres: pgCount };
  }

  console.log('\n[migrate] Migration verification summary:');
  let allMatched = true;
  for (const [t, s] of Object.entries(stats)) {
    const match = s.sqlite === s.postgres;
    if (!match) allMatched = false;
    console.log(`  - ${t}: SQLite = ${s.sqlite}, Postgres = ${s.postgres} ${match ? '✔' : '❌ MISMATCH'}`);
  }

  if (!allMatched) {
    throw new Error('Migration verification failed: row counts do not match!');
  }

  console.log('\n[migrate] All row counts verified successfully!');
  return stats;
}

function generateSqlDump(sqliteDb) {
  let sql = `-- SmartQueue SQLite to Supabase Postgres Migration Dump
-- Generated at: ${new Date().toISOString()}

`;
  for (const table of TABLES) {
    const rows = sqliteDb.prepare(`SELECT * FROM "${table.name}"`).all();
    if (!rows.length) continue;
    sql += `-- Table: ${table.name} (${rows.length} rows)\n`;
    const colList = table.cols.map((c) => `"${c}"`).join(', ');
    for (const row of rows) {
      const vals = table.cols.map((col) => {
        const val = row[col];
        if (val === null || val === undefined) return 'NULL';
        if (typeof val === 'number') return val;
        // Escape string
        return `'${String(val).replace(/'/g, "''")}'`;
      });
      sql += `INSERT INTO "${table.name}" (${colList}) VALUES (${vals.join(', ')}) ON CONFLICT DO NOTHING;\n`;
    }
    if (table.seq) {
      sql += `SELECT setval(pg_get_serial_sequence('${table.name}', 'id'), COALESCE((SELECT MAX(id) FROM "${table.name}"), 1));\n`;
    }
    sql += '\n';
  }
  return sql;
}

module.exports = { SCHEMA_SQL, RLS_SQL, TABLES, migrateData, generateSqlDump };

if (require.main === module) {
  const dbUrl = process.env.DATABASE_URL || process.env.SUPABASE_DB_URL;
  const sqlitePath = process.env.SQLITE_DB || path.resolve(__dirname, '../data/queue.db');
  const dumpPath = path.resolve(__dirname, '../supabase/migrations/20260310000001_migrated_data.sql');

  if (!dbUrl) {
    if (fs.existsSync(sqlitePath)) {
      console.log('[migrate] No DATABASE_URL specified. Generating Supabase SQL dump from SQLite...');
      const { DatabaseSync } = require('node:sqlite');
      const sqliteDb = new DatabaseSync(sqlitePath);
      const dump = generateSqlDump(sqliteDb);
      fs.mkdirSync(path.dirname(dumpPath), { recursive: true });
      fs.writeFileSync(dumpPath, dump, 'utf8');
      console.log(`[migrate] Migrated SQL dump written to: ${dumpPath}`);
    } else {
      console.log('[migrate] No DATABASE_URL specified and no SQLite file found.');
      console.log(`[migrate] Pre-generated migration dump is available at: ${dumpPath}`);
    }
    console.log('[migrate] To migrate directly into a live Supabase Postgres database, set DATABASE_URL:');
    console.log('          DATABASE_URL="postgresql://postgres:[password]@db.[project-ref].supabase.co:5432/postgres" npm run migrate');
    process.exit(0);
  }

  console.log('[migrate] Connecting to target Postgres database...');
  const pool = new pg.Pool({
    connectionString: dbUrl,
    ssl: dbUrl.includes('localhost') ? false : { rejectUnauthorized: false },
  });

  (async () => {
    // 1. Ensure schema and RLS policies exist
    console.log('[migrate] Ensuring schema is up to date...');
    await pool.query(SCHEMA_SQL);
    console.log('[migrate] Ensuring Row Level Security (RLS) is enabled...');
    await pool.query(RLS_SQL);

    // 2. If SQLite file exists, migrate live
    if (fs.existsSync(sqlitePath)) {
      console.log(`[migrate] Migrating live from SQLite database (${sqlitePath})...`);
      const { DatabaseSync } = require('node:sqlite');
      const sqliteDb = new DatabaseSync(sqlitePath);
      const stats = await migrateData(sqliteDb, pool);
      console.log('\n[migrate] Migration completed successfully!', stats);
    } else if (fs.existsSync(dumpPath)) {
      console.log(`[migrate] Applying pre-generated SQL migration dump (${dumpPath})...`);
      const dumpSql = fs.readFileSync(dumpPath, 'utf8');
      await pool.query(dumpSql);
      console.log('\n[migrate] Migration dump applied successfully!');
    } else {
      console.warn('[migrate] Neither SQLite database nor migration SQL dump found.');
    }
  })()
    .then(async () => {
      await pool.end();
      process.exit(0);
    })
    .catch(async (err) => {
      console.error('\n[migrate] Migration failed:', err);
      await pool.end();
      process.exit(1);
    });
}

