CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('government','hospital','corporate','bank')),
  address TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  radius_m INTEGER NOT NULL DEFAULT 150,
  open_min INTEGER NOT NULL,
  close_min INTEGER NOT NULL,
  slot_minutes INTEGER NOT NULL DEFAULT 15
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  slot_capacity INTEGER NOT NULL DEFAULT 4,
  avg_service_min INTEGER NOT NULL DEFAULT 6
);
CREATE INDEX IF NOT EXISTS ix_services_org ON services(org_id);

CREATE TABLE IF NOT EXISTS counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','paused','closed')),
  current_booking_id BIGINT
);
CREATE INDEX IF NOT EXISTS ix_counters_org ON counters(org_id);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  password_hash TEXT,
  google_sub TEXT UNIQUE,
  supabase_uid TEXT UNIQUE,
  totp_secret_enc TEXT,
  totp_enabled INTEGER NOT NULL DEFAULT 0,
  totp_last_step BIGINT NOT NULL DEFAULT 0,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','staff','admin','system')),
  strikes INTEGER NOT NULL DEFAULT 0,
  blocked_until BIGINT,
  org_id BIGINT REFERENCES organizations(id),
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users(lower(email));
CREATE INDEX IF NOT EXISTS ix_users_supabase_uid ON users(supabase_uid);

CREATE TABLE IF NOT EXISTS sessions (
  id_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mfa_ok INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  org_id BIGINT NOT NULL REFERENCES organizations(id),
  service_id BIGINT NOT NULL REFERENCES services(id),
  date TEXT NOT NULL,
  slot_index INTEGER NOT NULL,
  seat INTEGER NOT NULL,
  token_no INTEGER NOT NULL,
  token_code TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('appointment','walkin')),
  status TEXT NOT NULL CHECK (status IN ('booked','checked_in','called','done','no_show','cancelled')),
  counter_id BIGINT REFERENCES counters(id),
  deferrals INTEGER NOT NULL DEFAULT 0,
  reschedules INTEGER NOT NULL DEFAULT 0,
  reminder_sent INTEGER NOT NULL DEFAULT 0,
  away_since BIGINT,
  last_distance_m DOUBLE PRECISION,
  last_seen_at BIGINT,
  created_at BIGINT NOT NULL,
  checked_in_at BIGINT,
  called_at BIGINT,
  completed_at BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_bookings_seat
  ON bookings(service_id, date, slot_index, seat)
  WHERE status NOT IN ('cancelled','no_show');

CREATE INDEX IF NOT EXISTS ix_bookings_day ON bookings(org_id, date, status);
CREATE INDEX IF NOT EXISTS ix_bookings_user ON bookings(user_id, status);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  booking_id BIGINT,
  type TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'info',
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  read_at BIGINT
);
CREATE INDEX IF NOT EXISTS ix_notifications_user ON notifications(user_id, created_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  action TEXT NOT NULL,
  detail TEXT,
  ip TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS ix_audit_created ON audit_log(created_at);

CREATE TABLE IF NOT EXISTS risk_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  ip TEXT,
  score DOUBLE PRECISION,
  verdict TEXT NOT NULL,
  outcome TEXT NOT NULL,
  reasons TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_risk_created ON risk_events(created_at);
